### PR TITLE
README: typo fix

### PR DESCRIPTION
**Pull request by hellerve**
This PR fixes a little typo in the README (`stilll`->`still`).

Cheers

### CODE REVIEW

**Comment by ihucos** [comment]
Hello hellerve,

thank you very much for the contribution!
This is the first pull request for plash, I want to push this project forward much more.
From your Github project I see, that you work for the company where I used to work.
If you are interested in plash we can meet in Berlin and I can walk it trough and exchange ideas, I think this project has potential.

Cheers,
Irae

**Comment by hellerve** [comment]
Hey Irae,

it was a pleasure!

I’d love to contribute more, but I’m quite tied up with the projects I already work on at the moment, especially Carp. I’d still like to know a bit about this project—maybe Thursday?

Cheers
Veit

**Comment by ihucos** [comment]
Yes. You mean next Thursday at the Anno? I am there anyway and will bring my laptop. I could also come a little bit earlier, but don't know if its ok to use the meeting room for stuff unrelated to work.

**Comment by hellerve** [comment]
Yes, I do.

I don’t know either, since another company moved into the space as well. We’ll see!

**Comment by ihucos** [comment]
OK, great.
See you there.

**Pull request merged**
